import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import "../styles/design.css";
import Header from "@/components/header";
import { ThemeToggler } from "@components/theme-toggler";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="neon">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased test`}
      >
        <Header />
        {children}
        <div className="absolute top-2 right-2">
          <ThemeToggler />
        </div>
      </body>
    </html>
  );
}
